const WIDTH = 640;
const HEIGHT = 480;

const PLAYER_ACC = 250;
const PLAYER_SPEED_MAX = 100;
const PLAYER_FRICTION_RATE = 0.9;
const PLAYER_CONSTRAIN_HMIN = 0;
const PLAYER_CONSTRAIN_HMAX = WIDTH;
const PLAYER_CONSTRAIN_VMIN = HEIGHT * 0.5;
const PLAYER_CONSTRAIN_VMAX = HEIGHT;
const PLAYER_BULLET_WAITTIME = 100;

const BULLET_SPEED_VECTOR = {x: 0, y: -500};